title: Sarina Bloodgood
logo: /assets/img/sarina.png
description: Content Writer, Editor, and Digital Content Strategist based in Houston, TX. Specializing in content for B2B/B2C platforms.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
