title: Sarina Bloodgood
logo: /assets/img/sarina.png
description: <br>Content Writer, Editor, and Digital Content Strategist based in Houston, TX.<br><br>Specializing in content for B2B/B2C platforms.<br><br>[LinkedIn](https://www.linkedin.com/in/sarina-bloodgood/)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
