title: Sarina Bloodgood
logo: /assets/img/sarina.png
description: <br>Content Writer, Editor, and Digital Content Strategist based in Houston, TX.<br><br>Specializing in content for B2B/B2C platforms. Let\'s Connect! <a href="https://www.linkedin.com/in/sarina-bloodgood/">LinkedIn</a> | <a href="mailto:sarinabloodgood@gmail.com">Email</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
