title: Sarina Bloodgood
logo: /assets/img/sarina.png
description: <br>Digital Content Writer, Editor, and Strategist based in Houston, TX.<br><br>Specializing in B2B/B2C platforms. Connect via <a href="https://www.linkedin.com/in/sarina-bloodgood/">LinkedIn</a> | <a href="mailto:sarinabloodgood@gmail.com">Email</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
